# Data Configuration
data:
  base_dir: "data"
  image_size: 224
  batch_size: 32
  val_split: 0.2
  num_workers: 2

# Model Configuration
model_names:
  - "mobilenet_v2"
  - "vgg16"
  - "resnet50"
  - "vanilla_cnn"
  
# Training Configuration
training:
  epochs: 10
  learning_rate: 0.001
  weight_decay: 0.0001
  early_stopping_patience: 3
  lr_scheduler_patience: 3
  lr_scheduler_factor: 0.1

# Paths
paths:
  model_dir: "models"
  log_dir: "logs"
  results_dir: "results"

# MLflow Configuration
mlflow:
  experiment_name: "cataract-classification"
  tracking_uri: "logs/mlflow"